name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build

    - name: Deploy
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # REACT_APP_PLACES_API_KEY: ${{ secrets.REACT_APP_PLACES_API_KEY }}
        # REACT_APP_OPENUV_API_KEY: ${{ secrets.REACT_APP_OPENUV_API_KEY }}
        BRANCH: gh-pages
        FOLDER: build
